FROM openjdk:8-jdk-alpine
COPY target/courier-services-1.0-SNAPSHOT.jar CourierServices-1.0-SNAPSHOT.jar
CMD java -classpath src/main/java/com/everest/engineering EverestEngineeringApp
CMD java -classpath src/main/java/com/everest/engineering EverestEngineeringApp
